=== tparys/enctools/schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="enctools">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="chart_path" type="xs:string"/>
        <xs:element name="meta_path" type="xs:string"/>
        <xs:element name="land_path" type="xs:string" minOccurs="0"/>
        <xs:element name="land_layer" type="xs:string" minOccurs="0"/>
        <xs:element name="style_path" type="xs:string"/>
        <xs:element name="tile_size" type="xs:integer"/>
        <xs:element name="scale_base" type="xs:float"/>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== tparys/enctools/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<enctools xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="config.xsd">

  <!-- Location of ENC charts -->
  <chart_path>charts</chart_path>

  <!-- Location to store ENC metadata -->
  <meta_path>meta</meta_path>

  <!-- Enable or disable default land coverage -->
  <land_enabled>false</land_enabled>

  <!-- Land coverage file -->
  <land_path>path/to/GSHHS_l_L1.shp</land_path>

  <!-- Land coverage layer -->
  <land_layer>GSHHS_l_L1</land_layer>

  <!-- Location to color themes -->
  <theme_file>color-table.xml</theme_file>

  <!-- Location to store render styles -->
  <style_path>styles</style_path>

  <!-- Size of rendered tiles -->
  <tile_size>256</tile_size>

  <!-- Minimum presentation scale at tile zoom level 0 -->
  <scale_base>5e8</scale_base>

</enctools>
