=== tparys/enctools/schema/style.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- RGB or ARGB hex color code -->
  <xs:simpleType name="color_code">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9A-Fa-f]{3}|[0-9A-Fa-f]{4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8}"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Simple Style -->
  <xs:complexType name="simple_style">
    <xs:sequence>
      <xs:element name="fill_color" type="color_code" minOccurs="0"/>
      <xs:element name="line_color" type="color_code" minOccurs="0"/>
      <xs:element name="line_width" type="xs:integer" minOccurs="0"/>
      <xs:element name="marker_size" type="xs:integer" minOccurs="0"/>
      <xs:element name="text_color" type="color_code" minOccurs="0"/>
      <xs:element name="text_font" type="xs:string" minOccurs="0"/>
      <xs:element name="text_size" type="xs:integer" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Cutoff Style -->
  <xs:complexType name="cutoff_style">
    <xs:sequence>
      <xs:element name="value" type="xs:integer"/>
      <xs:element name="style" type="simple_style"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Simple Layer Styling -->
  <xs:complexType name="layer_style">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="style" type="simple_style"/>
      <xs:element name="cutoff_attr" type="xs:string"/>
      <xs:element name="cutoff" type="cutoff_style" minOccurs="0" maxOccurs="unlimited"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="style">
    <xs:complexType>
      <xs:sequence>

        <!-- Optional background, defaults to transparent if not set -->
        <xs:element name="background" minOccurs="0" type="color_code"/>
        <xs:element name="layer" type="layer_style" maxOccurs="unbounded"/>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== tparys/enctools/config/styles/dusk.xml
<?xml version="1.0" encoding="UTF-8"?>
<style xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="style.xsd">

  <!-- White Background -->
  <background>070707</background>

  <!-- Land Areas -->
  <layer>
    <name>LNDARE</name>
    <style>
      <fill_color>2C291B</fill_color>
      <line_color>252A2B</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Depth Areas -->
  <layer>
    <name>DEPARE</name>
    <style>
      <fill_color>070707</fill_color>
      <line_color>888</line_color>
      <line_width>1</line_width>
      <marker_size>0</marker_size>
    </style>
    <cutoff_attr>DRVAL1</cutoff_attr>
    <cutoff>
      <value>0</value>
      <style>
        <fill_color>15251f</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>2</value>
      <style>
        <fill_color>16232f</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>5</value>
      <style>
        <fill_color>151b21</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>10</value>
      <style>
        <fill_color>0c0e0f</fill_color>
      </style>
    </cutoff>
  </layer>

  <!-- Lake Areas -->
  <layer>
    <name>LAKARE</name>
    <style>
      <fill_color>16232f</fill_color>
      <line_color>888</line_color>
      <line_width>1</line_width>
      <marker_size>0</marker_size>
    </style>
  </layer>

  <!-- Shoreline Construction -->
  <layer>
    <name>SLCONS</name>
    <style>
      <fill_color>000</fill_color>
      <line_color>232C34</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Depth Contours -->
  <layer>
    <name>DEPCNT</name>
    <style>
      <fill_color>000</fill_color>
      <line_color>1A252F</line_color>
      <line_width>1</line_width>
      <marker_size>0</marker_size>
    </style>
  </layer>

  <!-- Depth Soundings -->
  <layer>
    <name>SOUNDG</name>
    <style>
      <text_color>474e4f</text_color>
      <text_font>monospace</text_font>
      <text_size>12</text_size>
    </style>
  </layer>

</style>

=== tparys/enctools/config/styles/base.xml
<?xml version="1.0" encoding="UTF-8"?>
<style xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="style.xsd">

  <!-- White Background -->
  <background>@CHWHT</background>

  <!-- Land Areas -->
  <layer>
    <name>LNDARE</name>
    <style>
      <fill_color>@LANDA</fill_color>
      <line_color>@CHBLK</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Depth Areas -->
  <layer>
    <name>DEPARE</name>
    <style>
      <fill_color>@DEPDW</fill_color>
      <line_color>@DEPCN</line_color>
      <line_width>1</line_width>
      <marker_size>0</marker_size>
    </style>
    <cutoff_attr>DRVAL1</cutoff_attr>
    <cutoff>
      <value>0</value>
      <style>
        <fill_color>@DEPIT</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>2</value>
      <style>
        <fill_color>@DEPVS</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>5</value>
      <style>
        <fill_color>@DEPMS</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>10</value>
      <style>
        <fill_color>@DEPMD</fill_color>
      </style>
    </cutoff>
  </layer>

  <!-- Lake Areas -->
  <layer>
    <name>LAKARE</name>
    <style>
      <fill_color>@DEPVS</fill_color>
      <line_color>@CHBLK</line_color>
      <line_width>1</line_width>
      <marker_size>0</marker_size>
    </style>
  </layer>

  <!-- Shoreline Construction -->
  <layer>
    <name>SLCONS</name>
    <style>
      <fill_color>@CHBLK</fill_color>
      <line_color>@CHBLK</line_color>
      <line_width>2</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Depth Contours -->
  <layer>
    <name>DEPCNT</name>
    <style>
      <line_color>@CHBLK</line_color>
      <line_width>1</line_width>
    </style>
  </layer>

  <!-- Depth Soundings -->
  <layer>
    <name>SOUNDG</name>
    <style>
      <text_color>@CHBLK</text_color>
      <text_font>monospace</text_font>
      <text_size>12</text_size>
    </style>
  </layer>

</style>

=== tparys/enctools/config/styles/night.xml
<?xml version="1.0" encoding="UTF-8"?>
<style xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="style.xsd">

  <!-- White Background -->
  <background>070707</background>

  <!-- Land Areas -->
  <layer>
    <name>LNDARE</name>
    <style>
      <fill_color>0D0A08</fill_color>
      <line_color>0E0F15</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Shoreline Construction -->
  <layer>
    <name>SLCONS</name>
    <style>
      <fill_color>000</fill_color>
      <line_color>141616</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Depth Contours -->
  <layer>
    <name>DEPCNT</name>
    <style>
      <fill_color>000</fill_color>
      <line_color>0C0D0E</line_color>
      <line_width>1</line_width>
      <marker_size>0</marker_size>
    </style>
  </layer>

  <!-- Depth Soundings -->
  <layer>
    <name>SOUNDG</name>
    <style>
      <fill_color>000</fill_color>
      <line_color>000</line_color>
      <line_width>0</line_width>
      <marker_size>0</marker_size>
    </style>
  </layer>

</style>

=== tparys/enctools/style.xml
<?xml version="1.0" encoding="UTF-8"?>
<style xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="style.xsd">

  <!-- White Background -->
  <background>fff</background>

  <!-- Land Areas -->
  <layer>
    <layer_name>LNDARE</layer_name>
    <fill_color>00c</fill_color>
    <line_color>00f</line_color>
    <line_width>1</line_width>
    <marker_size>5</marker_size>
  </layer>

  <!-- Shoreline Construction -->
  <layer>
    <layer_name>SLCONS</layer_name>
    <fill_color>000</fill_color>
    <line_color>000</line_color>
    <line_width>1</line_width>
    <marker_size>5</marker_size>
  </layer>

  <!-- Depth Contours -->
  <layer>
    <layer_name>DEPCNT</layer_name>
    <fill_color>000</fill_color>
    <line_color>777</line_color>
    <line_width>1</line_width>
    <marker_size>0</marker_size>
  </layer>

  <!-- Depth Soundings -->
  <layer>
    <layer_name>SOUNDG</layer_name>
    <fill_color>000</fill_color>
    <line_color>000</line_color>
    <line_width>0</line_width>
    <marker_size>0</marker_size>
  </layer>

</style>

=== tparys/enctools/config/styles/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<style xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="style.xsd">

  <!-- White Background -->
  <background>d3e9ed</background>

  <!-- Land Areas -->
  <layer>
    <name>LNDARE</name>
    <style>
      <fill_color>C8B87A</fill_color>
      <line_color>A8ACA1</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Depth Areas -->
  <layer>
    <name>DEPARE</name>
    <style>
      <fill_color>d3e9ed</fill_color>
      <line_color>888</line_color>
      <line_width>1</line_width>
      <marker_size>0</marker_size>
    </style>
    <cutoff_attr>DRVAL1</cutoff_attr>
    <cutoff>
      <value>0</value>
      <style>
        <fill_color>82b194</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>2</value>
      <style>
        <fill_color>73b5ee</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>5</value>
      <style>
        <fill_color>97c4f1</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>10</value>
      <style>
        <fill_color>b9d4e0</fill_color>
      </style>
    </cutoff>
  </layer>

  <!-- Lake Areas -->
  <layer>
    <name>LAKARE</name>
    <style>
      <fill_color>73b5ee</fill_color>
      <line_color>888</line_color>
      <line_width>1</line_width>
      <marker_size>0</marker_size>
    </style>
  </layer>

  <!-- Shoreline Construction -->
  <layer>
    <name>SLCONS</name>
    <style>
      <fill_color>000</fill_color>
      <line_color>989C92</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Depth Contours -->
  <layer>
    <name>DEPCNT</name>
    <style>
      <fill_color>000</fill_color>
      <line_color>888</line_color>
      <line_width>1</line_width>
      <marker_size>0</marker_size>
    </style>
  </layer>

  <!-- Obstructions -->
  <layer>
    <name>OBSTRN</name>
    <style>
      <fill_color>f88</fill_color>
      <line_color>f88</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Depth Soundings -->
  <layer>
    <name>SOUNDG</name>
    <style>
      <text_color>444</text_color>
      <text_font>monospace</text_font>
      <text_size>12</text_size>
    </style>
  </layer>

  <!-- Bouys (Lateral) -->
  <layer>
    <name>BOYLAT</name>
    <style>
      <fill_color>ffa500</fill_color>
      <line_color>ffa500</line_color>
      <line_width>0</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Wrecks -->
  <layer>
    <name>WRECKS</name>
    <style>
      <fill_color>f00</fill_color>
      <line_color>f00</line_color>
      <line_width>0</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

</style>

=== tparys/enctools/config/styles/standard.xml
<?xml version="1.0" encoding="UTF-8"?>
<style xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="style.xsd">

  <!-- No Data Available -->
  <background>@NODTA</background>

  <!-- Depth Areas -->
  <layer>
    <name>DEPARE</name>
    <style>
      <fill_color>@DEPDW</fill_color>
    </style>
    <cutoff_attr>DRVAL1</cutoff_attr>
    <cutoff>
      <value>0</value>
      <style>
        <fill_color>@DEPIT</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>2</value>
      <style>
        <fill_color>@DEPVS</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>5</value>
      <style>
        <fill_color>@DEPMS</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>10</value>
      <style>
        <fill_color>@DEPMD</fill_color>
      </style>
    </cutoff>
  </layer>

  <!-- Dredged Areas -->
  <layer>
    <name>DRGARE</name>
    <style>
      <fill_color>@DEPDW</fill_color>
      <line_color>@CHBLK</line_color>
      <line_width>1</line_width>
    </style>
    <cutoff_attr>DRVAL2</cutoff_attr>
    <cutoff>
      <value>0</value>
      <style>
        <fill_color>@DEPIT</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>2</value>
      <style>
        <fill_color>@DEPVS</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>5</value>
      <style>
        <fill_color>@DEPMS</fill_color>
      </style>
    </cutoff>
    <cutoff>
      <value>10</value>
      <style>
        <fill_color>@DEPMD</fill_color>
      </style>
    </cutoff>
  </layer>

  <!-- Land Areas -->
  <layer>
    <name>LNDARE</name>
    <style>
      <fill_color>@LANDA</fill_color>
      <line_color>@CHBLK</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Land Areas -->
  <layer>
    <name>BUAARE</name>
    <style>
      <fill_color>@LANDF</fill_color>
      <line_color>@CHBLK</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Lake Areas -->
  <layer>
    <name>LAKARE</name>
    <style>
      <fill_color>@DEPVS</fill_color>
      <line_color>@CHBLK</line_color>
      <line_width>1</line_width>
      <marker_size>0</marker_size>
    </style>
  </layer>

  <!-- Shoreline Construction -->
  <layer>
    <name>SLCONS</name>
    <style>
      <fill_color>@LANDA</fill_color>
      <line_color>@CHBLK</line_color>
      <line_width>1</line_width>
      <marker_size>5</marker_size>
    </style>
  </layer>

  <!-- Depth Contours -->
  <layer>
    <name>DEPCNT</name>
    <style>
      <line_color>@DEPCN</line_color>
      <line_width>1</line_width>
    </style>
  </layer>

  <!-- Depth Soundings -->
  <layer>
    <name>SOUNDG</name>
    <style>
      <text_color>@CHBLK</text_color>
      <text_font>monospace</text_font>
      <text_size>12</text_size>
    </style>
  </layer>

</style>
